name: "Unit tests"
on:
  pull_request: {}


jobs:
  test-emacs-28:
    # Run in a docker container
    runs-on: ubuntu-latest
    container:
      image: silex/emacs:28.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          apt-get -y update && \
              apt-get install -y python3
      - name: Emacs test
        run: emacs -batch -l ert -l anki-editor.el -l anki-editor-tests.el --eval "(let ((ert-batch-print-level 10) (ert-batch-print-length 120)) (ert-run-tests-batch-and-exit))"

  test-emacs-29:
    runs-on: ubuntu-latest
    container:
      image: silex/emacs:29.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          apt-get -y update && \
              apt-get install -y python3
      - name: Emacs test
        run: emacs -batch -l ert -l anki-editor.el -l anki-editor-tests.el --eval "(let ((ert-batch-print-level 10) (ert-batch-print-length 120)) (ert-run-tests-batch-and-exit))"

  # # TODO Turn on when ubuntu-24.04 workers are available
  # test-emacs-29:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install dependencies
  #       run: >
  #         sudo apt-get -y update &&
  #         sudo apt-get install -y emacs-nox

  #     - name: Emacs test
  #       run: emacs -batch -l ert -l anki-editor.el -l anki-editor-tests.el --eval "(let ((ert-batch-print-level 10) (ert-batch-print-length 120)) (ert-run-tests-batch-and-exit))"
